from contextlib import asynccontextmanager

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from starlette.middleware.gzip import GZipMiddleware
from starlette.middleware.trustedhost import TrustedHostMiddleware

from app.core.config import settings
from app.core.database import check_db, close_db, init_db
from app.core.jwks import jwks_client
from app.core.logging import configure_logging
from app.core.middleware import RequestContextMiddleware
from app.core.rate_limit import RateLimitMiddleware
from app.core.redis import redis_manager
from app.modules.ads.admin import router as ads_admin_router
from app.modules.ads.router import router as ads_router
from app.modules.announcements.admin import router as announcements_admin_router
from app.modules.announcements.router import router as announcements_router
from app.modules.banners.admin import router as banners_admin_router
from app.modules.banners.router import router as banners_router
from app.services.upload_client import upload_client

configure_logging()


@asynccontextmanager
async def lifespan(app: FastAPI):
    await init_db()
    await redis_manager.start()
    if settings.ENABLE_UPLOADS:
        await upload_client.start()
    await jwks_client.start()
    try:
        yield
    finally:
        await jwks_client.close()
        if settings.ENABLE_UPLOADS:
            await upload_client.close()
        await redis_manager.close()
        await close_db()


app = FastAPI(
    title="Livetse Promotion Service",
    version=settings.APP_VERSION,
    lifespan=lifespan,
    debug=False,
    docs_url="/docs" if settings.docs_enabled else None,
    redoc_url="/redoc" if settings.docs_enabled else None,
    openapi_url="/openapi.json" if settings.docs_enabled else None,
)

# Registration order matters: Starlette executes the last-added middleware
# first. RequestContext is registered after RateLimit so request IDs/security
# headers also wrap 429/503 responses generated by the limiter.
if settings.RATE_LIMIT_ENABLED:
    app.add_middleware(RateLimitMiddleware)
if settings.ENABLE_REQUEST_CONTEXT:
    app.add_middleware(RequestContextMiddleware)
if settings.ENABLE_GZIP:
    app.add_middleware(GZipMiddleware, minimum_size=settings.GZIP_MINIMUM_SIZE)
if settings.ENABLE_TRUSTED_HOSTS:
    app.add_middleware(TrustedHostMiddleware, allowed_hosts=settings.trusted_hosts)
if settings.ENABLE_CORS and settings.cors_origins:
    app.add_middleware(
        CORSMiddleware,
        allow_origins=settings.cors_origins,
        allow_credentials=settings.CORS_ALLOW_CREDENTIALS,
        allow_methods=settings.cors_allow_methods,
        allow_headers=settings.cors_allow_headers,
    )


@app.get("/health/live", tags=["Health"], include_in_schema=False)
async def liveness():
    return {"status": "ok", "service": settings.APP_NAME, "version": settings.APP_VERSION}


@app.get("/health/ready", tags=["Health"], include_in_schema=False)
async def readiness():
    if settings.HEALTH_READY_DB_CHECK_ENABLED:
        try:
            await check_db()
        except Exception as exc:
            raise HTTPException(status_code=503, detail="database unavailable") from exc
    return {"status": "ready"}


if settings.ENABLE_ANNOUNCEMENTS:
    app.include_router(announcements_router, prefix="/announcements")
    app.include_router(announcements_admin_router, prefix="/announcements")
if settings.ENABLE_BANNERS:
    app.include_router(banners_router, prefix="/banners")
    app.include_router(banners_admin_router, prefix="/banners")
if settings.ENABLE_ADS:
    app.include_router(ads_router, prefix="/ads")
    app.include_router(ads_admin_router, prefix="/ads")
